apiVersion: v1
kind: Pod
metadata:
  name: app-pod-with-labels
  labels:
    environment: dev
    app: http-server
spec:
  containers:
    - name: app-kuber-container
      image: nginx:latest
      ports:
        - containerPort: 80
