apiVersion: v1
kind: Pod
metadata:
  name: app-pod-with-gpu
  labels:
    app: http-server
spec:
  # Под может быть назначен только ноде, имеющую метку gpu=true
  nodeSelector:
    gpu: "true"
  containers:
    - name: app-kuber-container
      image: nginx:latest
      ports:
        - containerPort: 80
