apiVersion: v1
kind: Pod
metadata:
  name: hostpath-pod
spec:
  containers:
    - name: test-container
      image: nginx:latest
      volumeMounts:
        - name: test-volume
          mountPath: /test-pd
  volumes:
    # Хранишице с таким типом не будет удалено при удалении пода. Но оно имеет недостатки, связанные с безопасностью
    - name: test-volume
      # hostPath предназначен для каких-то системных подов, которым необходим доступ внутрь самой ноды, для каких-нибудь драйверов.
      # Поэтому рекомендуют режим readOnly, чтобы под не мог испортить или принести какую-либо угрозу безопасности вашей ноде
      # Но бывают ситуации, когда подам нужен доступ к ноде, где они располагаются, к примеру им нужен доступ к папке /var/lib/docker или системным папкам /sys и т.д., но это нужно делать тогда, когда вы знаете, что делаете
      hostPath:
        path: /data
        # Задаём поведение хранилища (Directory - проверяет, существует ли указанная папка или нет)
        type: Directory
      # type: DirectoryOrCreate # Создать папку по указанному пути, если её не существует
      # type: File FileOrCreate и т. д.
