apiVersion: v1
kind: Service
metadata:
  name: my-single-pod-1-service
spec:
  selector:
    project: my-project-1
  ports:
    - name: app-listener
      protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
