apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment-env-secret-file
  labels:
    app: my-deployment-env-secret-file
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-server-1
  template:
    metadata:
      labels:
        app: http-server-1
    spec:
      containers:
        - name: my-container
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: secrets
              mountPath: "/etc/secrets"
      volumes:
        - name: secrets
          secret:
            secretName: secret-data
            defaultMode: 0400
