apiVersion: batch/v1
kind: CronJob
metadata:
  name: my-cron-job-without-timeout-fail-counts
spec:
  schedule: "*/1 * * * *"
  # Здесь мы уже не задавали startingDeadlineSeconds, но крон-джоба также выдаст ошибку,
  # поскольку за 7000 сек (116 мин) счётчик насчитает 116 запуска джоб,
  # которым concurrencyPolicy: Forbid не даст запуститься. А если более 100 джоб по крону не смогут
  # запустятся, то крон-джоба выдаст ошибку
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          containers:
            - name: hello
              image: busybox
              command:
                - "/bin/sh"
                - "-c"
                - "date; echo Hello world; sleep 7000"
          restartPolicy: Never
