apiVersion: batch/v1
kind: CronJob
metadata:
  name: my-cron-job-allow
spec:
  schedule: "*/1 * * * *"
  # Разрешает запускать следующую джобу, если предыдущая не завершилась
  # По умолчанию (Allow)
  concurrencyPolicy: Allow
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hello
              image: busybox
              imagePullPolicy: IfNotPresent
              command:
                - "/bin/sh"
                - "-c"
                - "date; echo Hello world; sleep 140"
          restartPolicy: OnFailure
