apiVersion: batch/v1
kind: CronJob
metadata:
  name: my-cron-job-with-timeout-fail-counts
spec:
  schedule: "*/1 * * * *"
  # Здесь крон-джоба выдаст ошибку, поскольку за 8000 сек (133 мин) счётчик насчитает 133 запуска джоб,
  # которым concurrencyPolicy: Forbid не даст запуститься. А если более 100 джоб по крону не смогут
  # запустятся, то крон-джоба выдаст ошибку
  startingDeadlineSeconds: 8200
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          containers:
            - name: hello
              image: busybox
              command:
                - "/bin/sh"
                - "-c"
                - "date; echo Hello world; sleep 8000"
          restartPolicy: Never
