env:
  open:
    STORAGE: local
    DISABLE_API: false
    # Разрешить анонимным пользователям доступ скачивать chart-репозитории
    AUTH_ANONYMOUS_GET: true
  secret:
    BASIC_AUTH_USER: admin
    BASIC_AUTH_PASS: mypassword
