apiVersion: batch/v1
kind: Job
metadata:
  name: job-pi-completions
spec:
  # Джоба запустится 3 раза последовательно друг за другом (когда одна завершается, запускается другая)
  completions: 3
  backoffLimit: 4
  template:
    spec:
      containers:
        - name: pi
          image: perl
          command: ["perl", "-Mbignum=bpi", "-wle", "print(2000)"]
      restartPolicy: Never
