apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment-volume-empty-dir
  labels:
    app: kuber
spec:
  replicas: 3
  selector:
    matchLabels:
      app: http-server
  template:
    metadata:
      labels:
        app: http-server
    spec:
      containers:
        - name: kuber-app-1
          image: bakavets/kuber
          ports:
            - containerPort: 8000
          volumeMounts:
            - mountPath: /cache-1
              name: cache-volume
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
          # - mountPath: /usr/share/nginx/html
            - mountPath: /cache-2
              name: cache-volume
              # subPath: data
      # При удалении пода файлы в хранилище (с типом emptyDir) тоже будут удалены
      volumes:
        - name: cache-volume
          emptyDir: {}
