apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: http-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  # Такой тип используется для отладки (доступа к сервису, минуя Ingress)
  type: NodePort
