apiVersion: v1
kind: Service
metadata:
  name: my-single-pod-2-service
  owner: MyOwner
spec:
  selector:
    project: my-project-2
  ports:
    - name: app-listener-2
      protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
